# The main CI of Hibernate Search is http://ci.hibernate.org/. Travis CI can be
# used in github forks. https://travis-ci.org/hibernate/hibernate-search is
# therefore deactivated. Activating Travis for your own fork is as easy as
# activating it in the travis site of your fork.

sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
git:
  # Required in order for Sonar to retrieve blame information
  depth: false
addons:
  apt:
    packages:
      - oracle-java8-installer
  sonarcloud:
    organization: "hibernate"
    token:
      secure: "iiKx4XPJTJAL/++XVVCxmVKdu+0RYh2FaZtSyzMFdWK/RQ3J+4XaEn4yIe4o+znBJ5KWqK7uaKJHmnsaj9Diac2FujCkRC6O+iInPGDIhKyWqqDm8sM4BikXZZnLS4p6Pu8KUHggY9whJTq1SW8JG3yL1Y8p3Efa+PyniWtDj4U2f5FOeqBw4/wdPl6K7K9fYwbgXauvkYiZK0G4KRGCWnamKiREcJ39F6kcqWUARCSUIKcRkkPcUIkzTgXqEAJRzpNpQ0eNNzsnqKkVOT4SX6QRlTQfmq9rC4E2ADYYHWLSt9P+afU2HPwCe8gDpjbH+6UMVohQHxLW+WZx35RwAfWSjQPqmjKUXACcgjb1bJ8fsodMriAa25h5EQDW/UDRy+ppLOKBGzAdAqg/lWNGpiO8g/6kZwR+iRlxlnUka858HP4OQkAM4ix28S+GRPCxc9l/06AdF+1lIoPopi6aGrVzX6FyFMahtSxE9bhGg7vU0t3aljW1wbwzGB+UoBpD5Mpff6Kd8pGAGtGzKDPnVBah8M4s5IpYYwdui4i4gKSK7kQdytijzvoy0htcP5XKWtAW2ZQdN9xJJi4+BQPERgz607aUKcuLyEIGh/LQCzhKlqybNHYim8C72IUwRd+d5Ep23BHm91wVXR5a6GGvwL6lR6XbEfh3+u6TguO6ZdM="
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
install:
  # The Maven install provided by Travis is outdated, use Maven wrapper to get the latest version
  - mvn -N io.takari:maven:wrapper
  - ./mvnw -v
script:
  - ./mvnw -Pcoverage -Pjqassistant clean install javadoc:javadoc sonar:sonar
after_success:
  - ./mvnw coveralls:report
before_cache:
  # Do not put the artifacts we just built into the cache
  - rm -r $HOME/.m2/repository/org/hibernate/search/v6poc/
