# The main CI of Hibernate Search is http://ci.hibernate.org/. Travis CI can be
# used in github forks. https://travis-ci.org/hibernate/hibernate-search is
# therefore deactivated. Activating Travis for your own fork is as easy as
# activating it in the travis site of your fork.

sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
git:
  # Required in order for Sonar to retrieve blame information
  depth: false
addons:
  apt:
    packages:
      - oracle-java8-installer
  sonarcloud:
    organization: "hibernate"
    token:
      secure: "iiKx4XPJTJAL/++XVVCxmVKdu+0RYh2FaZtSyzMFdWK/RQ3J+4XaEn4yIe4o+znBJ5KWqK7uaKJHmnsaj9Diac2FujCkRC6O+iInPGDIhKyWqqDm8sM4BikXZZnLS4p6Pu8KUHggY9whJTq1SW8JG3yL1Y8p3Efa+PyniWtDj4U2f5FOeqBw4/wdPl6K7K9fYwbgXauvkYiZK0G4KRGCWnamKiREcJ39F6kcqWUARCSUIKcRkkPcUIkzTgXqEAJRzpNpQ0eNNzsnqKkVOT4SX6QRlTQfmq9rC4E2ADYYHWLSt9P+afU2HPwCe8gDpjbH+6UMVohQHxLW+WZx35RwAfWSjQPqmjKUXACcgjb1bJ8fsodMriAa25h5EQDW/UDRy+ppLOKBGzAdAqg/lWNGpiO8g/6kZwR+iRlxlnUka858HP4OQkAM4ix28S+GRPCxc9l/06AdF+1lIoPopi6aGrVzX6FyFMahtSxE9bhGg7vU0t3aljW1wbwzGB+UoBpD5Mpff6Kd8pGAGtGzKDPnVBah8M4s5IpYYwdui4i4gKSK7kQdytijzvoy0htcP5XKWtAW2ZQdN9xJJi4+BQPERgz607aUKcuLyEIGh/LQCzhKlqybNHYim8C72IUwRd+d5Ep23BHm91wVXR5a6GGvwL6lR6XbEfh3+u6TguO6ZdM="
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
before_install:
  # Build options must be set before install, so that we properly retrieve *all* the necessary dependencies
  - BUILD_OPTIONS='-Pdist -Pcoverage -Pjqassistant'
install:
  # The Maven install provided by Travis is outdated, use Maven wrapper to get the latest version
  - mvn -N io.takari:maven:wrapper
  - ./mvnw -v
  # First run to download most Maven dependencies without logging and to install our artifacts for the early checkstyle execution
  # We want to start as many plugins as possible (so that their dependencies are downloaded),
  # but we want the plugins to be skipped if they are not essential,
  # because they will be re-executed later and we don't want to waste time.
  - ./mvnw $BUILD_OPTIONS -B -q clean install javadoc:javadoc coveralls:report sonar:sonar
    -DskipTests -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true -Djqassistant.skip=true
    -Dcoveralls.skip=true -Dsonar.skip=true
script:
  # We run checks first to fail fast if there is a styling error, then we run the actual build.
  # Note sonar must be ran in the "script:" section in order to benefit from Travis caching.
  - ./mvnw $BUILD_OPTIONS checkstyle:check
    && ./mvnw $BUILD_OPTIONS install javadoc:javadoc sonar:sonar -Dcheckstyle.skip
after_success:
  - ./mvnw $BUILD_OPTIONS coveralls:report
before_cache:
  # Do not put the artifacts we just built into the cache
  - rm -r $HOME/.m2/repository/org/hibernate/search/v6poc/
